### PR TITLE
Nb walkthrough cleaning

### PR DESCRIPTION
**Pull request by nsbatra**
This is the first of a few website pages that will take the user through the AJS template, using the Am Timan Chad dataset. This page's focus is the initial data import and cleaning steps.

I am still adding to this page and will let the group know when done. Feel free to comment/revise anytime.

### CODE REVIEW

**Comment by epiamsterdam** [comment]
Hi Neale - have gone through the Template walk trhough - i see what you are aiming towards and it looks good in general.
A few very nitpicky issues:
* the links for the R markdown intro  and R markdown authoring basics look a little odd at the top - should there be a section there called 'background to R markdowns?"
* I can draft you some introductory text for the outbreak, the surveillance and the linelist - how long should it be?
* Section on Template header, should the picture go below the text? In the same section you mention "the introductions..."; shouldnt we refer to it exactly as how it is referred to in the markdown "The introduction to this template"
* There are no instructions anywhere on which markdown to open ? Shouldnt we inlcude a small section on that - opening the correct template?
* Where will the datasets be  stored that people can use together with this walkthrough?
* Section around clean_labels coding - can we include an example from a variable that is poorly named in the raw dataset and what happens after we apply clean_labels coding?
* The formatting in the population count section is a little weird - shouldnt we put numbers for each possible option on how to include population data>?

**Comment by epiamsterdam** [comment]
* do we need to to include a section that describes the data we have access to? Or perhaps it is rather self explanatory?
* in the sections where you still have to insert links, Zhian likes to note them with 'TODO' first so that it is easy to spot these missing links for the final push to the website
* Section "AJS/HEV outbreak in Am Timan, Chad (2016-2017)" =- maybe move the context description to above the screenshot of the article? And then keep the link in that section too?
* can we move the parts around packages on this link https://r4epis.netlify.com/outbreaks/ inot the main walkthrough pages?
* do we need something around setting the working directory?
* There is a line in there that starts with "Create lists of symptom variables already switched “med” variables to these ones, but some do not apply and must be removed from the list, such as convulsions and history of fever?" - feels a bit random in the middle there

**Comment by kdoyle514** [comment]
https://r4epis.netlify.com/outbreaks/
- Need to update package list

**Comment by aspina7** [comment]
nice! looks like you are getting a couple errors that dont produce analyses later down .... maybe because of the subpaging? 
You might want to consider having one cleaning file that you source in each of the sub pages, so that way you dont need to repeat the same thing in each rmd to make sure the data is there and correct! 
(sorry if you have already done this and the errors are something else totally random! just thought i would throw it in there in case!)

**Review by aspina7 — APPROVED** [review]
approving for merge so we can get the overview

**Pull request merged**
