### PR TITLE
Nb r basics

### PR DESCRIPTION
**Pull request by nsbatra**
Adding a subpage on R Basics to Trainings. Trying to follow the training plan google doc and to strike a balance between covering the essential items for new R users and yet NOT being comprehensive.
 
I start with how R is object-oriented and then continue into how objects have classes, structures, and are assigned value. 

Then I get into functions, arguments, pipe operator, and will direct to package installation elsewhere.

Finish with miscellaneous such as syntax, errors/warnings, searching for answers to questions, etc.

Sections still to add: logical operators and checks, keyboard shortcuts, more advanced stuff

### CODE REVIEW

**Comment by aspina7** [comment]
Nice! 
Just a few things from me (theres probably more functional ways of me commenting but too lazy to look rn so just chucking it all here): 
- the google doc is not gospel at all! feel free to re-arrange, change, omit whatever you think! 
- maybe more for @zkamvar is it possible to have the headings within R basics as like sub sub headings on that list on the right there? just to make navigating easier.... 
- dont think you need to have add _print_ to print(reporting_week), just reporting_week
- we probably need to reference the radboud course for that image of blocks - or redraw one ourselves. (ref: "introduction in using R" - Gerjon Hannink, Radboud University Medical Centre, 2019) @epiamsterdam should probably check that we are even allowed to use this. 
- maybe make the bit about using dollars to get to variables a subheading? so it stands out more after that table. 
- Maybe dont use the hist function as we wont be using it later, may a good place to just introduce a basic table? (though getting pictures and colours in early is always nice...) 
- for the pipe operator, mention that it is part of the dplyr package (although actually it is the magritr package being called by dplyr) - anyway the point is that they cant just use it off the bat. 
- so maybe mention packages before pipes? 
- Maybe we want to chuck calculations and general syntax with logical operators and the stuff earlier on?

**Comment by epiamsterdam** [comment]
Hi neale - have gone through these pages and a few comments:

* In the orientation to R studio section can we include some text that links the set up of R studio to STATA: e.g. console = command line in STATA, source pane=do file in STATA, script=do file for STATA users
* the section on 'uncomment' is a bit unclear. i think we need to show what we mean - i.e. show one line commented and one line uncommented and how the difference looks
* online resources: should we include the RECON slack option?
* R basic section - AJS is miss-spelled as AJS; in the part where you show the %>% with linelist_cleaned, can we make it clear that if you write linelist_cleaned<- linelist_cleaned%>% will overwrite the existing version of linelist_cleaned - so you need to be sure that whatever comes after the %>% you really want to keep

**Comment by zkamvar** [comment]
Hi Neale, is this ready to go or are you still working on it?

**Comment by nsbatra** [comment]
Adding a few last items now.

**Comment by zkamvar** [comment]
Be sure to flag me here when it's ready for review.

**Comment by nsbatra** [comment]
@zkamvar These three pages (RStudio, RMarkdown, and R Basics) are ready for review if you have a moment! Thank you.

**Comment by kdoyle514** [comment]
- "Functions with Multiple Arguments" uses descriptive() as an example -- need to change to tab_linelist()

**Review by aspina7 — APPROVED** [review]
approving for merge to get overall view

**Pull request merged**
